FLabel CHECKSTROBE  \ 00F
FLabel NUMBERSIDE  \ 032
FLabel DC1 \ 038
FLabel DC2  \ 03E
FLabel CHECKNOSTROBE  \ 03F
FLabel KEYTABLE  \ 04A
FLabel BLOCKTRANS  \ 08A
FLabel BLOCKSETUP  \ 098
FLabel BLK1 \ 0A3
FLabel BLKJOIN  \ 0A5
FLabel UNF  \ 0AC
FLabel FOK  \ 0B3
FLabel TESTSOL  \ 0B6
FLabel TS1  \ TS1
FLabel SEESAVE \ 0D2
FLabel BB1  \ 100
FLabel COMPUTE  \ 109
FLabel COMCHECK  \ 123
FLabel CPARETURN  \ 166
FLabel NUMBR \ 190
FLabel NORMAL \ 1A2
FLabel SHUFFLE  \ 1A6
FLabel SEARCHHISTORY \ 1B8
FLabel SETHISTORY  \ 1BF
FLabel NOSET  \ 1C6
FLabel DECIMALN
FLabel DCM1  \ 1D0  ??
FLabel DCM2  \ 1E6
FLabel DCM3  \ 1F0
FLabel DCMJOIN  \ 1F8
FLabel BB2  \ 200
FLabel OWNSHIP  \ 209
FLabel BOTHBLANK  \ 21F
FLabel VITIATE1  \ 22E
FLabel VITIATE2  \ 235
FLabel NEEDBOTH  \ 249
FLabel JOINOS  \ 25A
FLabel COURSE  \ 274
FLabel COURSEOK  \ 283
FLabel FIRST  \ 2A1
FLabel SETCHECK1  \ 2AA
FLabel SAMEFS  \
FLabel SECOND  \ 2CC
FLabel SETCHECK2  \ 2D5
FLabel SAME12  \ 2E2
FLabel ALLIN  \ 2E6
FLabel BB3  \ 300
FLabel TARGETNUMBER  \ 307
FLabel NOK  \ 316
FLabel RANGE  \ 332
FLabel RANGEOK  \ 341
FLabel BEARING  \ 35D
FLabel BEARINGOK  \ 36C
FLabel TIME  \ 38A
FLabel TIMEOKOK  \ 399
FLabel SPEED  \ 3B7
FLabel SPEEDOK  \ 3C6
FLabel UNSET7  \ 3E4
FLabel BB4  \ 400
FLabel SAVED  \ 407
FLabel SAVEIT  \ 423
FLabel SAVEND  \ 430
FLabel CPA  \ 43B
FLabel TARGETSHIP  \ 44E
FLabel STATUSIN  \ 462
FLabel STATUSOUT  \ 476
FLabel WAIT5  \ 48A
FLabel WAIT5LOOP  \ 48E
FLabel DISPLAY  \ 493
FLabel CLOK  \ 4A4
FLabel DCLCK  \ 4BB
FLabel WAITMS  \ 4CA
FLabel CLEARKEY  \ 4DE
FLabel CPACOMPUTE  \ 500
FLabel POSY  \ 565
FLabel POSX  \ 573
FLabel NOROTATE  \ 57F
FLabel TIMECK  \ 5CF
FLabel FLOOP  \
FLabel FINDCPA  \ 658
FLabel NOBACKROTATE1  \ 68F
FLabel GOCDTIME  \ 6EB
FLabel HROUT  \ 6F1
FLabel FINDCANDS  \ 716
FLabel NOBACKROTATE2  \ 738
FLabel ATLASTOHATLAST  \ 7EB
FLabel REVOLVE  \ 7ED
FLabel ZERORAM  \ 829
FLabel ZRAM  \ 82A
FLabel LOADBRG  \ 830
FLabel LOADRNG  \ 839
FLabel TRANSPART  \ 842
FLabel LOADTIMELO  \ 84B
FLabel LOADTIMEHI  \ 854
FLabel DORAM  \ 85B
FLabel FBACK  \ 861
FLabel NONZERO  \ 86C
FLabel SETUP  \ 86D
FLabel FALLTHRU5  \ 87A
FLabel SETUP1  \ 883
FLabel SETUP2  \ 88E
FLabel SETUP3  \ 899
FLabel SETUP4  \ 8A4
FLabel DVRT  \ 8AF
FLabel DV4 \ 8BD
FLabel DV6  \ 8CD
FLabel CHKPT  \ 8D4
FLabel DV1  \ 8DF
FLabel DV2  \ 8EA
FLabel ATLASTDIV  \
FLabel CORDIC \ 900
FLabel SKIP1  \ 92A
FLabel JOIN1  \ 93C
FLabel SKIP2  \ 957
FLabel JOIN2  \ 967
FLabel MLOOP  \ 96B  ????
FLabel LOOPP  \ 96E
FLabel SKIPX  \ 979
FLabel JOINX  \ 97B
FLabel ATLAST  \ 981
FLabel CPLRT  \ 982
FLabel COMPL  \ 983
FLabel TENS  \ 98B
FLabel ADRT  \ 99A
FLabel ADDR  \ 99B
FLabel SBRT  \ 9AD
FLabel SUBT  \ 9B0
FLabel OOK  \ 9B8
FLabel TRANSLOOP
FLabel CORDICAT
FLabel ZEROLOOPAT  \ A03
FLabel SWITCH1  \ A17
FLabel SWITCH2  \ A26
FLabel SWITCH3 \ A4D
FLabel SWITCH4  \ A66
FLabel MLOOPAT  \ A6A
FLabel LOOPAT  \ A6D
FLabel SKIPXAT \ A78
FLabel JOINXAT \ A7A
FLabel CHECK \ A80
FLabel ATLASTAT \ AA1
FLabel ROTATE  \ AA2
FLabel SZ  \ AAD
FLabel JZ  \ AAF
FLabel NOSHIFTX  \ AC8
FLabel SX  \ AD1
FLabel JX  \ AD3
FLabel NOSHIFTY \ AE0
FLabel SY  \ AE8
FLabel SHIFT \ AEB
FLabel MINORLOOP \ AED
FLabel FERT  \ B00
FLabel FETCHLOOP \ B02
FLabel NOINC  \ B0E
FLabel TWOPI
FLabel MINPI
FLabel MIN3PI2
FLabel MINPI2
FLabel INVK
FLabel MINVK
FLabel A1
FLabel A2
FLabel A3
FLabel A4
FLabel A5
FLabel DAY
FLabel HRSPERMIN
FLabel MLRT \ B8A
FLabel ZEROLOOPM  \ B8F
FLabel ML4  \ BA5
FLabel ML6  \ BB6
FLabel ML1  \ BBB
FLabel ML2  \ BBE
FLabel ML3  \ BCB
FLabel ML5  \ BDA
FLabel ML8  \ BE7
FLabel ML7  \ BF4
FLabel MADRT  \ C00
FLabel STMAD  \ C01
FLabel SKIPML  \ C0A
FLabel DECDIV \ C0D
FLabel ZEROR  \ C15
FLabel LOCATEZERO  \ C1E
FLabel FOUNDZERO  \ C29
FLabel COPYA  \ C20
FLabel LOCATEZERO1 \ C3E
FLabel FOUNDZERO1 \ C48
FLabel NOUNDERF \ C60
FLabel COPYC1  \ C66
FLabel PASTCOPY1  \ C74
FLabel DIV  \ C7E
FLabel SUB0  \ C80
FLabel SUB1   \ C82
FLabel SUB2  \ C87
FLabel COMPLEMENT  \ C8E
FLabel CHECKCARRY  \ C9C
FLabel CARRYOUT  \ CA1
FLabel ADD4  \ CA5
FLabel SKIPADD \ CB5
FLabel ENDDIVIDE  \ CBF
FLabel COPYC2  \ CC3
FLabel FILLZ \ CCD
FLabel PASTFILL  \ CD2
FLabel DOVERFLOW  \ CD3






